# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: be7a527d1aa61e6f302c3b9b26ec896462c9cea8c50698646bca936a45ae42341b18d34ba10dbbf3d15b2b33df69c35f5568fbdb8b060132738c28303f3c6ac8

test:
  secret_key_base: bde84c18fe8ccc31b7dede8ed18d8bb0601789f6141000cda8f3c7a9592cbc5f801501d890547a296945292514dd8518f12acba683eb84e3f676ab9510077d55

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
